### ISSUE TITLE
Prediction on colab for single premise is 1 minute

### ISSUE THREAD

**Issue by mirfan899** [luka-group/lite#4]
I have used your model on colab and did the prediction but it takes around 1 minute and 4 seconds for single premise. Is there a way to optimize the time for prediction? 

Here is my prediction code. I'm using batch size 32.

```python
premise = "On late Monday night , 30th Nov 2009 , Bangladesh Police arrested Rajkhowa somewhere near Dhaka ."
entity = ""
label = ""
res_buffer = {}
for batch_id in range(0, len(type_vocab), 32):
    dat_buffer = type_vocab[batch_id: batch_id + 32]
    sequence = [f'{premise}{2 * tokenizer.sep_token}{entity} is a {label}.' for label in dat_buffer]
    inputs = tokenizer(sequence, padding=True, return_tensors='pt').to(device)
    outputs = model(**inputs)[:, -1]
    confidence = outputs.detach().cpu().numpy().tolist()
    for idx in range(len(dat_buffer)):
        res_buffer[dat_buffer[idx]] = confidence[idx]

confidence_ranking = {labels: res_buffer[labels] for labels in res_buffer
                      if res_buffer[labels] > 0.0}
confidence_ranking = {k: v for k, v in sorted(confidence_ranking.items(), key=lambda item: -item[1])}


res = {}

confidence_ranking = {labels: res_buffer[labels] for labels in res_buffer
                             if res_buffer[labels] > 0.3}
confidence_ranking = {k: v for k, v in sorted(confidence_ranking.items(), key=lambda item: -item[1])}
res['confidence_ranking'] = confidence_ranking
```

**Comment by VincentLeebang** [comment]
> I have used your model on colab and did the prediction but it takes around 1 minute and 4 seconds for single premise. Is there a way to optimize the time for prediction?
> 
> Here is my prediction code. I'm using batch size 32.
> 
> ```python
> premise = "On late Monday night , 30th Nov 2009 , Bangladesh Police arrested Rajkhowa somewhere near Dhaka ."
> entity = ""
> label = ""
> res_buffer = {}
> for batch_id in range(0, len(type_vocab), 32):
>     dat_buffer = type_vocab[batch_id: batch_id + 32]
>     sequence = [f'{premise}{2 * tokenizer.sep_token}{entity} is a {label}.' for label in dat_buffer]
>     inputs = tokenizer(sequence, padding=True, return_tensors='pt').to(device)
>     outputs = model(**inputs)[:, -1]
>     confidence = outputs.detach().cpu().numpy().tolist()
>     for idx in range(len(dat_buffer)):
>         res_buffer[dat_buffer[idx]] = confidence[idx]
> 
> confidence_ranking = {labels: res_buffer[labels] for labels in res_buffer
>                       if res_buffer[labels] > 0.0}
> confidence_ranking = {k: v for k, v in sorted(confidence_ranking.items(), key=lambda item: -item[1])}
> 
> 
> res = {}
> 
> confidence_ranking = {labels: res_buffer[labels] for labels in res_buffer
>                              if res_buffer[labels] > 0.3}
> confidence_ranking = {k: v for k, v in sorted(confidence_ranking.items(), key=lambda item: -item[1])}
> res['confidence_ranking'] = confidence_ranking
> ```

Hi,
Are u doing the inference on GPU or CPU? From my observations, it takes 30 seconds to do predictions for one instance with a 10k type vocab.

**Comment by mirfan899** [comment]
Of course I'm using GPU. Well I'm not getting 30 seconds, its 66 seconds. How did you calculate the time. Here is time on single prediction.
![time](https://user-images.githubusercontent.com/3822565/181688984-6d82dba7-7074-42ac-a5ee-d2df4f25aaa4.png)

**Comment by VincentLeebang** [comment]
Hi, I've tested your code on my machine with batch_size=32 and It takes 19.6s to finish. I think the bottleneck here may be the GPU performance. Our GPU is RTX TITAN while CoLab may provide TESLA K80 which has a lower clock speed.
